version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolio
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
