name: Test MERN Stack

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server
        
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Copy environment file
        run: cp .env.example .env
      
      - name: Run server tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/portfolio_test
          
  test-client:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build check
        run: npm run build --if-present
        
      - name: Run client tests
        run: npm test --if-present